# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170127_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_status',
            new_name='message_state',
        ),
    ]
