# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170127_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=20)),
                ('native', models.CharField(max_length=6, null=True)),
                ('learner', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MessageRoom',
        ),
    ]
