# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20170129_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_state',
        ),
    ]
